---
title: "Guidance Database"
---


# Methods guidance papers for overviews

```{r, echo = FALSE}

dat3 <- readxl::read_excel(here::here("data", "methods.xlsx"))

```

Total number of publications: `r nrow(dat3)` 

Last update: `r format(Sys.Date(), "%d\\/%m\\/%Y")`



```{r, layout="l-page-outset", echo=FALSE}

#<a href="/about/about_team.htm">team</a> 
  
dat3$doi <- paste0('<a target="_blank" rel="noopener noreferrer" href="', dat3$doi,'">',dat3$doi ,"</a>")

DT::datatable(dat3, 
             options = list(searchHighlight = TRUE, 
                            fixedHeader = TRUE, 
                            colReorder = FALSE, 
                            dom = 'Blfrtip', 
                            buttons = list("searchPanes", "excel", "csv"),
                            language = list(searchPanes = list(collapse = "Search Filters")),
                            columnDefs = list(list(
    searchPanes = list(show = TRUE), targets = c(1, 3, 4) )),                            
 initComplete = DT::JS(
    "function(settings, json) {",
    "$(this.api().table().header()).css({'background-color': '#3e831d', 'color': '#ffffff'});",
    "}")

),
             escape = FALSE, 
             extensions = c('Select', 'SearchPanes', 'Buttons',
                            'Responsive',
                            'FixedHeader', 'ColReorder')
) |> 
DT::formatStyle('doi',  color = 'blue') |>
DT::formatStyle('publication year', textAlign = 'center') 

```


