---
title: "OMG Project"
site: distill::distill_website
#listing: posts
---


This website presents the first database that contains a large number of overviews of reviews. The database provides a
comprehensive source that can be freely used by all researchers to easily identify all overviews of reviews on a specific topic, to avoid duplication of effort and reduce research waste. 
The database will be regularly updated with new data and studies.


## Codebook

**first_author:** the name of the first author

**title:** the publication title 

**publication_year:** the year when the article was published in the issue

**title_terminology:** nomenclature related to the evidence synthesis (e.g., overview, meta-review, umbrella review) reported in the tile of the article

**journal:** the journal where the article was published

**corresponding_author_country:** the country of origin of the corresponding author. If the corresponding author reports multiple institutional affiliations from different countries, the country is chosen based on the domain of the correspondence email address

**corresponding_author_affiliation:** the affiliation (e.g., university, institute) of the corresponding author

**subject_area:** main subject area (based on the list of subject areas provided by medRxiv)

**icd_11_disease:** disease (based on the International Classification of Diseases 11th Revision[ICD-11])

**icd_11_parent:** parent category of the disease (based on the International Classification of Diseases 11th Revision[ICD-11])                   
**doi:** digital object identifier of the publication                
**design:** the type of studies that were considered for inclusion (only systematic reviews or other study types)

**number_of_SRs:** number of included systematic reviews

**intervention:** interventions that were examined in the article

**type:** type of overview based on the research questions (e.g., intervention, association, prediction, economic evaluation etc.)

**method:** methodological approach used in overview (e.g., systematic, living, rapid, scoping etc.)
