---
title: "Methodological Overviews Database"
---

```{r, echo = FALSE}

dat2 <- readxl::read_excel(here::here("data", "all_overviews-current_1.0.xlsx")) |>
  dplyr::filter(method == "methodological") |>
  dplyr::select(-c(`research question`, `method`))

```


# Total number of publications: `r nrow(dat2)` 

Last update: `r format(Sys.Date(), "%d\\/%m\\/%Y")`

```{r, layout="l-page-outset", echo=FALSE}

#<a href="/about/about_team.htm">team</a> 
  
dat2$doi <- paste0('<a target="_blank" rel="noopener noreferrer" href="', dat2$doi,'">',dat2$doi ,"</a>")

DT::datatable(dat2, 
             options = list(searchHighlight = TRUE, 
                            fixedHeader = TRUE, searchBuilder = TRUE,
                            dom = 'Qlfrtip', colReorder = FALSE, 
                            #language = list(searchPanes = list(collapse = "Search Filters")),
                            #scrollX = TRUE, 
                            #buttons = list("searchPanes"),
columnDefs = list(
  #list(searchPanes = list(show = T), targets = c(1, 3, 4, 5, 7, 12:14) ),
    
list(
  targets = 2,
  render = DT::JS(
    "function(data, type, row, meta) {",
    "return type === 'display' && data.length > 100 ?",
    "'<span title=\"' + data + '\">' + data.substr(0, 100) + '...</span>' : data;",
    "}"))

    ),
 initComplete = DT::JS(
    "function(settings, json) {",
    "$(this.api().table().header()).css({'background-color': '#E68613', 'color': '#f2f2f2'});",
    "}")

),
             escape = FALSE, 
             extensions = c('Select', 'SearchPanes', 'Buttons',"SearchBuilder",
                            'Responsive',
                            'FixedHeader', 'ColReorder')
) |> 
DT::formatStyle('doi',  color = 'blue') |>
DT::formatStyle('publication year', textAlign = 'center')  

```


